const Login = 'login';
const Register = 'register';
const ForgetPassword = 'forgetpassword';
const ChangePassword = 'change_password';
const GetProfile = 'buyer-data';
const UpdateProfile = 'buyer_update';
const GetShops = 'shops';
const GetCategories = 'categotries';
const GetProducts = 'products';
const ContactInfo = 'contactinfo';
const GetBanners = 'banners';
const GetAddresses = 'addresses';
const AddToCart = 'addtocart';
// http://beautiheath.com/sub/eshop/api/buyers/product/wishlists get
//http://beautiheath.com/sub/eshop/api/buyers/addto/wishlists?productId=8 post
const GetCarts = 'product/carts';
const ContactUs = 'sendhelp';
const wishlists = 'addto/wishlists';
const AllOffers = 'alloffers';
const AddReview = 'add-review';
const AllReviews = 'all-reviews';
const AddAddress = 'add-adress';
const DeleteAddress = 'delete-adress';
const GetOrder = 'get-buyer-order';
const SendOrder = 'send-order';
const DeleteOrder = 'order-status';
